AWSTemplateFormatVersion: "2010-09-09"
Description: BayesBet Project Cloudformation Template

Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String

  VpcCIDR:
    Description: Please enter the IP range (CIDR notation) for this VPC
    Type: String
    Default: 10.192.0.0/16

  PublicSubnet1CIDR:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the first Availability Zone
    Type: String
    Default: 10.192.10.0/24

Resources:
  # Create VPC with internet gateway connected to single public subnet for Batch
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: !Ref PublicSubnet1CIDR
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} Public Subnet (AZ1)

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} Public Routes

  DefaultPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: InternetGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet1

  NoIngressSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: "no-ingress-sg"
      GroupDescription: "Security group with no ingress rule"
      VpcId: !Ref VPC

  EcrRepository:
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: ${EnvironmentName}-repo
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} ECR Repository

  BatchServiceRole:
    Type: AWS::IAM:Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-27'
        Statement:
          - Effect: Allow
            Principal:
              Service: batch.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSBatchServiceRole

  EcsInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2008-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.cm
            Action:
              sts:AssumeRole
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceForEC2Role
        Path: /

  EcsInstanceS3BucketPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub ${EnvironmentName}-EcsInstanceS3BucketPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Action:
            - 's3:List*'
          Resource:
            - !Sub 'arn:aws::s3:::${S3Bucket}'
      Roles:
        - !Ref EcsInstanceRole

  EcsInstanceS3ObjectsPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub ${EnvironmentName}-EcsInstanceS3ObjectsPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Action:
            - 's3:Get*'
            - 's3:Put*'
          Resource:
            - !Sub 'arn:aws::s3:::${S3Bucket}/*'
      Roles:
        - !Ref EcsInstanceRole

  EcsInstanceDynamoDbPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub ${EnvironmentName}-EcsInstanceDynamoDbPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Action:
            - 'dynamodb:List*'
            - 'dynamodb:DescribeReservedCapacity*'
            - 'dynamodb:DescribeLimits'
            - 'dynamodb:DescribeTimeToLive'
          Resource: '*'
        - Effect: Allow
          Action:
            - 'dynamodb:BatchGet*'
            - 'dynamodb:DescribeStream'
            - 'dynamodb:DescribeTable'
            - 'dynamodb:Get*'
            - 'dynamodb:Query'
            - 'dynamodb:Scan'
            - 'dynamodb:BatchWrite*'
            - 'dynamodb:CreateTable'
            - 'dynamodb:Delete*'
            - 'dynamodb:Update*'
            - 'dynamodb:PutItem'
          Resource: !GetAtt DynamoDBTable.Arn
      Roles:
        - !Ref EcsInstanceRole

  IamInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles: [!Ref EcsInstanceRole]

  ComputeEnvironment:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      Type: MANAGED
      ServiceRole: !GetAtt BatchServiceRole.Arn
      ComputeEnvironmentName: ${EnvironmentName} Batch Compute Environment
      ComputeResources:
        Type: EC2
        MinvCpus: 0
        DesiredvCpus: 0
        MaxvCpus: 8
        InstanceTypes:
          - optimal
        Subnets:
          - !Ref PublicSubnet1
        SecurityGroupIds:
          - !Ref NoIngressSecurityGroup
        InstanceRole: !Ref IamInstanceProfile
      State: ENABLED

  JobQueue:
    Type: AWS::Batch::JobQueue
    Properties:
      JobQueueName: ${EnvironmentName} Batch Job Queue
      Priority: 1
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment:!Ref ComputeEnvironment
      State: ENABLED

  JobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      JobDefinitionName: ${EnvironmentName} Model Update Batch Job
      Type: container
      ContainerProperties:
        Image: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${EnvironmentName}-repo:latest'
        Vcpus: 4
        Memory: 8000
        Privileged: false
        Environment:
          - Name: S3_BUCKET_NAME
            Value: bayes-bet
          - Name: DYNAMODB_TABLE_NAME
            Value: bayes-bet-table

  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Delete
    Properties:
      BucketName: bayes-bet-prod

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Description: BayesBet Model Results Table
    Properties:
      TableName: bayes-bet-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: League
          AttributeType: S
        - AttributeName: PredictionDate
          AttributeType: S
      KeySchema:
        - AttributeName: League
          KeyType: HASH
        - AttributeName: PredictionDate
          KeyType: RANGE
  
Outputs:
  VPC:
    Description: A reference to the created VPC
    Value: !Ref VPC

  PublicSubnet1:
    Description: A reference to the public subnet in the 1st Availability Zone
    Value: !Ref PublicSubnet1

  NoIngressSecurityGroup:
    Description: Security group with no ingress rule
    Value: !Ref NoIngressSecurityGroup

