# Generated by Django 2.2.4 on 2019-08-05 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plot',
        ),
    ]
