# This is a basic workflow to help you get started with Actions

name: BayesBet CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events to dev and master
  push:
    branches: [ dev, master ]
  pull_request:
    branches: [ dev, master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install pipenv
        run: pip install pipenv
      - name: Run model tests
        run: |
          cd model
          pipenv sync
          pipenv run pytest --runslow
