# This is a basic workflow to help you get started with Actions

name: BayesBet Test

# Controls when the action will run. 
on:
  # Triggers the workflow on pull request events to dev and master    
  pull_request:
    branches: [ dev, master ]
    paths:
      - .github/workflows/test.yml
      - model/bayesbet/**
      - model/Pipfile*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: model
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install pipenv
        run: |
          pip install pipenv

      - name: Cache pipenv virtualenv
        id: cache-pipenv
        uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock', '**/requirements.txt') }} 

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: pipenv install

      - name: Run model tests
        run: |
          pipenv run python -m pytest --runslow
